# .github/secret-scanning.yml
allowlist:
  # Firebase API keys are safe to expose in client code,
  # so we suppress them here to avoid false positives.
  secrets:
    - type: "Google API Key"
      reason: "Firebase apiKey is a public identifier, not a secret"
